#include <stdexcept>

int main () {
    throw std::exception();
}
